spring:
  profiles:
    active: local
  jpa:
    show-sql: true


database:
  url: jdbc:postgresql://localhost:25432/kakaofinance
  username: kakaoapp
  password: '!q2w3e4r'



---
spring:
  profiles:
    active: dev